package com.ole.constant;

public interface ResponseCode {
	int SUCCESS_CODE = 0;
	int REGISTRATION_ERROR_CODE = 100;
	int PROFILE_EDIT_ERROR_CODE = 101;
	int EXAM_ADD_ERROR_CODE = 102;
	int EXAM_FETCH_ERROR_CODE = 103;
	
	int USER_NOT_EXIST_ERROR_CODE = 104;
	int UN_AUTHORIZED_ACCESS_ERROR_CODE = 105;
	int QUESTION_ADD_ERROR_CODE = 106;
	int EXAM_UPDATE_ERROR_CODE = 107;
	int QUESTION_FETCH_ERROR_CODE = 108;
	
	int QUESTION_UPDATE_ERROR_CODE = 109;
	int EXAM_DELETE_ERROR_CODE = 110;
	int QUESTION_DELETE_ERROR_CODE = 111;
	int PROFILE_DELETE_ERROR_CODE = 112;
	
	int ANSWER_ADD_ERROR_CODE = 113;
	int ANSWER_FETCH_ERROR_CODE = 114;
	int RESULT_ADD_ERROR_CODE = 115;
	int RESULT_FETCH_ERROR_CODE = 116;
	int HISTORY_FETCH_ERROR_CODE = 117;
	
	int ANSWER_DELETE_ERROR_CODE = 118;
}
